--删除字段
ALTER TABLE NEWLAND.CHANGEDATA DROP COLUMN REMARK1;
ALTER TABLE NEWLAND.CHANGEDATA DROP COLUMN REMARK2;
ALTER TABLE NEWLAND.CHANGEDATA DROP COLUMN REMARK4;
ALTER TABLE NEWLAND.CHANGEDATA DROP COLUMN birthday;
ALTER TABLE NEWLAND.CHANGEDATA ADD COLUMN REMARK3 VARCHAR;

--增加字段
ALTER TABLE NEWLAND.CHANGEDATA ADD COLUMN timestamp Timestamp ;
